// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "りんご電卓",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "りんご電卓",
            targets: ["AppModule"],
            bundleIdentifier: "com.KC3-2023-C.calculator-for-iPad",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .calculator),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(path: "/Users/norihito/Desktop/University/KC3/KC3_2023_W/2023_C/calculator-for-iPad.core")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "CalculatorCore", package: "calculator-for-iPad.core")
            ],
            path: "."
        )
    ]
)